export enum TokenizerGoal { 
  InlineCode = 1,
  Footnote,
  Spoiler,
  Parenthesized,
  SquareBracketed,
  Action,
  ParenthesizedInRawText,
  SquareBracketedInRawText,
  CurlyBracketedInRawText,
  ParenthesizedLinkUrl,
  SquareBracketedLinkUrl,
  CurlyBracketedLinkUrl,
  Link,
  LinkUrl,
  RevisionInsertion,
  RevisionDeletion,
  Audio,
  Image,
  Video,
  MediaUrl,
  NakedUrl
}
